### ISSUE TITLE
Managing Locale issue

### ISSUE THREAD

**Issue by araujogo** [auth0-extensions/auth0-account-link-extension#137]
Tried to find more what Locale is about on the menu, but a popup with [Object] appears

**Comment by keyboSlice** [comment]
Hi, we're also experiencing this, did you manage to work around it?

We tried manually sending a PUT request to the locales endpoint, which does set the strings but it removes the custom HTML that we'd added for the page 🙃

**Comment by bernardwolff** [comment]
Hello @araujogo and @keyboSlice, as a workaround, you can get the Manage locales page to load if you copy the address of the link and paste it into the browser's address bar.

**Comment by ajubin** [comment]
For me, available locales are the following
<img width="1069" alt="image" src="https://github.com/auth0-extensions/auth0-account-link-extension/assets/14874974/0b5a6c2f-c2fe-4352-a5cb-744ddf985326">


All my users are French so I found a hack to override content this way: 

```css
/* On my custom.css file */

#message {
  font-size: 0;
}
#message::after {
  /* Original content: It looks like you have another account with the same email address. We recommend you link these accounts. You may sign in with Auth0 to link accounts. */
  content: "Nous avons détecté qu'un autre compte associé à cette adresse email existe déjà. Pour le lier à ce nouveau moyen de connexion, veuillez cliquer sur 'Continuer' pour vous authentifier avec l'autre compte.";
  /* reset to original properties */
  font-size: 16px;
  display: block;
}

```
